### ISSUE TITLE
ModuleNotFoundError: No module named 'data.single_dataset'

### ISSUE THREAD

**Issue by labx12** [Chanuku/Semi_ref2sketch_code#1]
hello, trying to run test.py but have been running into the following
```
Traceback (most recent call last):
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\test.py", line 10, in <module>
    opt = TestOptions().parse()  # get test options
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\options\base_options.py", line 115, in parse
    opt = self.gather_options()
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\options\base_options.py", line 81, in gather_options
    dataset_option_setter = data.get_option_setter(dataset_name)
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\__init__.py", line 43, in get_option_setter
    dataset_class = find_dataset_using_name(dataset_name)
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\__init__.py", line 26, in find_dataset_using_name
    datasetlib = importlib.import_module(dataset_filename)
  File "C:\Users\lbend\anaconda3\envs\line\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'data.single_dataset'
```
this is the command im using to try this:
`python test.py --name semi_unpair --model unpaired --epoch 100 --dataroot "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\datasets\ref_unpair" --dataset_mode single`
not sure where i'm going wrong - somewhat new to this, let me know if you have any ideas

**Comment by Chanuku** [comment]
hi, can you try test_dir.py instead?

**Comment by labx12** [comment]
Same issue
```
semi_ref2sketch_code>python test_dir.py --name semi_unpair --model unpaired --epoch 100 --dataroot "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\datasets\ref_unpair" --dataset_mode single
Traceback (most recent call last):
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\test_dir.py", line 57, in <module>
    opt = TestOptions().parse()  # get test options
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\options\base_options.py", line 115, in parse
    opt = self.gather_options()
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\options\base_options.py", line 81, in gather_options
    dataset_option_setter = data.get_option_setter(dataset_name)
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\__init__.py", line 43, in get_option_setter
    dataset_class = find_dataset_using_name(dataset_name)
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\__init__.py", line 26, in find_dataset_using_name
    datasetlib = importlib.import_module(dataset_filename)
  File "C:\Users\lbend\anaconda3\envs\line\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'data.single_dataset'
```

**Comment by Chanuku** [comment]
can you remove --dataset_mode ?

**Comment by labx12** [comment]
removing that gets me this:
```
loading the model from ./checkpoints\semi_unpair\100_net_G_A.pth
loading the model from ./checkpoints\semi_unpair\100_net_G_B.pth
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 36.856 M
[Network G_B] Total number of parameters : 24.591 M
-----------------------------------------------
creating web directory ./results/semi_unpair\test_100
Traceback (most recent call last):
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\test_dir.py", line 87, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\__init__.py", line 91, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\lbend\anaconda3\envs\line\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\lbend\anaconda3\envs\line\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\lbend\anaconda3\envs\line\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lbend\anaconda3\envs\line\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\data\unaligned_dataset.py", line 53, in __getitem__
    index_B = index % self.B_size
ZeroDivisionError: integer division or modulo by zero
```
command: `python test_dir.py --name semi_unpair --model unpaired --epoch 100 --dataroot "C:\Users\lbend\Documents\Image 2 Line\semi_ref2sketch_code\datasets\ref_unpair"`

**Comment by Chanuku** [comment]
I think error occur because there are no files in testB folder, however it's not necessary for the inference task.
I'll fix the code later, sorry for delay
If you want to run the code, just put any one file in testB folder
Thank you

**Comment by labx12** [comment]
Thanks for all the help with troubleshooting, that seemed to be it. 
Also another question if you're willing, is it possible to keep images at their native resolution & crop size? been messing with --load_size & --crop_size but I cant seem to get it exact.

**Comment by Chanuku** [comment]
Hi you can achieve the naitive resolution and crop size by using test_dir
You can find it on result/{name}/dir_free folder
